In [1]:
import numpy as np
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
matrix = np.random.rand(4, 4)
print("Matrix:\n", matrix)
print("Max Value:", np.max(matrix))
print("Min Value:", np.min(matrix))

Matrix:
 [[3.65706479e-01 8.11345131e-01 9.36348823e-01 6.73443351e-01]
 [3.12420351e-04 7.06624344e-01 7.88936692e-01 9.36407158e-01]
 [3.92701231e-01 6.46628034e-01 7.16765972e-01 6.61714453e-01]
 [6.75298178e-01 7.75637812e-01 8.26973044e-01 8.84338312e-01]]
Max Value: 0.9364071581519378
Min Value: 0.0003124203510245227


In [4]:
arr = np.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = a + b
multiplication = a * b
print("Addition:", addition)
print("Multiplication:", multiplication)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [6]:
arr = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
